language: python
dist: xenial
python:
  - "2.7"
before_install:
    - sudo apt-get update -qq
    - sudo apt-get install python-bluetooth -qq -y
    - pip install pyserial==3.1.1
    - pip install coveralls
install: pip install -q -e .
script: python setup.py test
after_success:
  - coverage run --source=openxc setup.py test
  - coveralls
